//{{NO_DEPENDENCIES}}
#pragma once

#define ID_TYPELIB_INTEROP              1
#define ID_SHADER_PACKAGE               9000
#define IDD_SPLASH_SCREEN               9001

// Strings
#define IDS_APP_CL_BAD_PARAM            9100
#define IDS_APP_CL_BUFFERS              9101
#define IDS_APP_CL_CLEAR_SCORES         9102
#define IDS_APP_CL_DEFAULT_OPTIONS      9103
#define IDS_APP_CL_FIRST_RUN            9104
#define IDS_APP_CL_FPS_OFF              9105
#define IDS_APP_CL_FPS_ON               9106
#define IDS_APP_CL_FS_OFF               9107
#define IDS_APP_CL_FS_ON                9108
#define IDS_APP_CL_HELP                 9109
#define IDS_APP_CL_PADDING              9110
#define IDS_APP_CL_SOUND_OFF            9111
#define IDS_APP_CL_SOUND_ON             9112
#define IDS_APP_CL_VSYNC_OFF            9113
#define IDS_APP_CL_VSYNC_ON             9114
#define IDS_APP_CL_WIN8_SERVER          9115
#define IDS_APP_COMPANY                 9116
#define IDS_APP_LOG_WITH_TIME           9117
#define IDS_APP_OPTIONS_FILE            9118
#define IDS_APP_PARSE_COMMAND_LINE      9119
#define IDS_APP_RESTORING_STATE         9120
#define IDS_APP_SAVING_STATE            9121
#define IDS_APP_SCORES_FILE             9122
#define IDS_APP_SHUTDOWN                9123
#define IDS_APP_STARTUP                 9124
#define IDS_APP_STARTUP_DONE            9125
#define IDS_BUTTON_NAME                 9126
#define IDS_COMBINED_JOYSTICK_NAME      9127
#define IDS_ERR_ADAPTER                 9128
#define IDS_ERR_DIRECT3D                9130
#define IDS_ERR_DIRECTINPUT             9131
#define IDS_ERR_DIRECTXMATH             9132
#define IDS_ERR_MOUSE                   9133
#define IDS_ERR_RENDER_2D               9134
#define IDS_ERR_RENDER_3D               9135
#define IDS_ERR_RENDER_TARGET           9136
#define IDS_ERR_TOUCH                   9137
#define IDS_ERR_DEPTH_BUFFER            9138
#define IDS_KEYBOARD_NAME               9139
#define IDS_LEGACY_JOYSTICK_NAME        9140
#define IDS_MOUSE_NAME                  9141
#define IDS_STICK0                      9142
#define IDS_STICK1                      9143
#define IDS_STICK_POV                   9144
#define IDS_STICK_UNKNOWN               9145
#define IDS_TOUCH_NAME                  9146
#define IDS_TRIGGER_UNKNOWN             9147
#define IDS_XBOX_BUTTON_A               9148
#define IDS_XBOX_BUTTON_B               9149
#define IDS_XBOX_BUTTON_BACK            9150
#define IDS_XBOX_BUTTON_LSHOULDER       9151
#define IDS_XBOX_BUTTON_LTHUMB          9152
#define IDS_XBOX_BUTTON_RSHOULDER       9153
#define IDS_XBOX_BUTTON_RTHUMB          9154
#define IDS_XBOX_BUTTON_START           9155
#define IDS_XBOX_BUTTON_X               9156
#define IDS_XBOX_BUTTON_Y               9157
#define IDS_XBOX_JOYSTICK_NAME          9158
#define IDS_XBOX_LTRIGGER               9159
#define IDS_XBOX_PAD_DIGITAL            9160
#define IDS_XBOX_PAD_LEFT               9161
#define IDS_XBOX_PAD_RIGHT              9162
#define IDS_XBOX_RTRIGGER               9163
#define IDS_APP_CLEANUP                 9164
#define IDS_APP_LOADING_OPTIONS         9165
#define IDS_APP_SAVING_OPTIONS          9166
#define IDS_APP_RUN_MAIN_LOOP           9168
#define IDS_APP_WINDOW_CLOSE            9169
#define IDS_APP_WINDOW_DESTROY          9170
#define IDS_APP_INIT_DIRECT3D           9171
#define IDS_APP_INIT_RENDER_TARGET      9172
#define IDS_APP_INIT_DEPTH_BUFFER       9173
#define IDS_APP_INIT_RENDER_2D          9174
#define IDS_APP_INIT_RENDER_3D          9175
#define IDS_APP_INIT_KEYBOARD           9176
#define IDS_APP_INIT_MOUSE              9177
#define IDS_APP_INIT_TOUCH              9178
#define IDS_APP_INIT_JOYSTICKS          9179
#define IDS_APP_INIT_AUDIO              9180
#define IDS_ERR_KEYBOARD                9181
#define IDS_ERR_AUDIO                   9182
#define IDS_APP_SUSPEND                 9183
#define IDS_APP_RESUME                  9184
#define IDS_APP_WINDOW_CREATED          9185
#define IDS_APP_WINDOW_CREATING         9186
#define IDS_STATUS_LOADING              9187
#define IDS_STATUS_READY                9188
#define IDS_APP_CL_AUTOMATION           9189
